### PR TITLE
AddedMyPage

### PR DESCRIPTION
**Pull request by NickAdvisor95**
# Title

### Types of Changes

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Dependency change

### Checklist

- [ ] My code follows the code style of this project

### CODE REVIEW

**Comment by NiPavel** [comment]
<b>Hui</b>

**Review by alechkos — COMMENTED** [review]
Test approved

**Review by NiPavel — APPROVED** [review]
Super!

**Comment by alechkos** [comment]
Test finished

**Pull request closed without merging**
